export default jogos = [
  {
    rodada: 10,
    time1: "São Paulo",
    time2: "Mirassol",
    data: "2025-05-24",
    hora: "18:30",
    canal: "",
    estadio: "Morumbis",
    campionato: "Brasileirão",
  },
  {
    rodada: 10,
    time1: "Fluminense",
    time2: "Vasco da Gama",
    data: "2025-05-24",
    hora: "18:30",
    canal: "",
    estadio: "Maracanã",
    campionato: "Brasileirão",
  },
  {
    rodada: 10,
    time1: "Atlético-MG",
    time2: "Corinthians",
    data: "2025-05-24",
    hora: "21:00",
    canal: "",
    estadio: "Arena MRV",
    campionato: "Brasileirão",
  },
  {
    rodada: 10,
    time1: "Grêmio",
    time2: "Bahia",
    data: "2025-05-25",
    hora: "11:00",
    canal: "",
    estadio: "Arena do Grêmio",
    campionato: "Brasileirão",
  },
  {
    rodada: 10,
    time1: "Palmeiras",
    time2: "Flamengo",
    data: "2025-05-25",
    hora: "16:00",
    canal: "",
    estadio: "Allianz Parque",
    campionato: "Brasileirão",
  },
  {
    rodada: 10,
    time1: "Sport Recife",
    time2: "Internacional",
    data: "2025-05-25",
    hora: "16:00",
    canal: "",
    estadio: "Ilha do Retiro",
    campionato: "Brasileirão",
  },
  {
    rodada: 10,
    time1: "Vitória",
    time2: "Santos",
    data: "2025-05-25",
    hora: "18:30",
    canal: "",
    estadio: "Barradão",
    campionato: "Brasileirão",
  },
  {
    rodada: 10,
    time1: "Fortaleza",
    time2: "Cruzeiro",
    data: "2025-05-25",
    hora: "20:30",
    canal: "",
    estadio: "Castelão",
    campionato: "Brasileirão",
  },
  {
    rodada: 10,
    time1: "RB Bragantino",
    time2: "Juventude",
    data: "2025-05-26",
    hora: "20:00",
    canal: "",
    estadio: "Nabi Abi Chedid",
    campionato: "Brasileirão",
  },
  {
    rodada: 10,
    time1: "Botafogo",
    time2: "Ceará",
    data: "2025-06-04",
    hora: "20:00",
    canal: "",
    estadio: "Nilton Santos",
    campionato: "Brasileirão",
  },
  {
    rodada: 11,
    time1: "Bahia",
    time2: "São Paulo",
    data: "2025-05-31",
    hora: "18:30",
    canal: "",
    estadio: "Arena Fonte Nova",
    campeonato: "Brasileirão",
  },
  {
    rodada: 11,
    time1: "Vasco da Gama",
    time2: "RB Bragantino",
    data: "2025-05-31",
    hora: "21:00",
    canal: "",
    estadio: "Estádio São Januário",
    campeonato: "Brasileirão",
  },
  {
    rodada: 11,
    time1: "Mirassol",
    time2: "Sport Recife",
    data: "2025-06-01",
    hora: "11:00",
    canal: "",
    estadio: "Estádio José Maria de Campos Maia",
    campeonato: "Brasileirão",
  },
  {
    rodada: 11,
    time1: "Juventude",
    time2: "Grêmio",
    data: "2025-06-01",
    hora: "16:00",
    canal: "",
    estadio: "Estádio Alfredo Jaconi",
    campeonato: "Brasileirão",
  },
  {
    rodada: 11,
    time1: "Santos",
    time2: "Botafogo",
    data: "2025-06-01",
    hora: "16:00",
    canal: "",
    estadio: "Estádio Vila Belmiro",
    campeonato: "Brasileirão",
  },
  {
    rodada: 11,
    time1: "Ceará",
    time2: "Atlético-MG",
    data: "2025-06-01",
    hora: "18:30",
    canal: "",
    estadio: "Estádio Castelão",
    campeonato: "Brasileirão",
  },
  {
    rodada: 11,
    time1: "Corinthians",
    time2: "Vitória",
    data: "2025-06-01",
    hora: "18:30",
    canal: "",
    estadio: "Neo Química Arena",
    campeonato: "Brasileirão",
  },
  {
    rodada: 11,
    time1: "Flamengo",
    time2: "Fortaleza",
    data: "2025-06-01",
    hora: "18:30",
    canal: "",
    estadio: "Maracanã",
    campeonato: "Brasileirão",
  },
  {
    rodada: 11,
    time1: "Cruzeiro",
    time2: "Palmeiras",
    data: "2025-06-01",
    hora: "19:30",
    canal: "",
    estadio: "Estádio Mineirão",
    campeonato: "Brasileirão",
  },
  {
    rodada: 11,
    time1: "Internacional",
    time2: "Fluminense",
    data: "2025-06-01",
    hora: "20:30",
    canal: "",
    estadio: "Estádio Beira-Rio",
    campeonato: "Brasileirão",
  },
  {
    rodada: 12,
    time1: "RB Bragantino",
    time2: "Bahia",
    data: "2025-06-12",
    hora: "19:00",
    canal: "PREMIERE",
    estadio: "Estádio Nabi Abi Chedid",
    campionato: "Brasileirão"
  },
  {
    rodada: 12,
    time1: "Vitória",
    time2: "Cruzeiro",
    data: "2025-06-12",
    hora: "19:00",
    canal: "PREMIERE",
    estadio: "Estádio Manoel Barradas",
    campionato: "Brasileirão"
  },
  {
    rodada: 12,
    time1: "Fortaleza",
    time2: "Santos",
    data: "2025-06-12",
    hora: "19:30",
    canal: "RECORD TV/ CAZÉ TV",
    estadio: "Estádio Plácido Aderaldo Castelo",
    campionato: "Brasileirão"
  },
  {
    rodada: 12,
    time1: "Grêmio",
    time2: "Corinthians",
    data: "2025-06-12",
    hora: "20:00",
    canal: "GLOBO/ PREMIERE",
    estadio: "Arena do Grêmio",
    campionato: "Brasileirão"
  },
  {
    rodada: 12,
    time1: "Atlético-MG",
    time2: "Internacional",
    data: "2025-06-12",
    hora: "21:30",
    canal: "",
    estadio: "Arena MRV",
    campionato: "Brasileirão"
  },
  {
    rodada: 12,
    time1: "São Paulo",
    time2: "Vasco da Gama",
    data: "2025-06-12",
    hora: "21:30",
    canal: "",
    estadio: "MorumBIS",
    campionato: "Brasileirão"
  }
  rodada: 13,
    time1: "Bahia",
    time2: "Atlético-MG",
    data: "2025-07-11",
    hora: "23:00",
    canal: "PREMIERE",
    estadio: "Arena Fonte Nova",
    campionato: "Brasileirão"
  },
  {
    rodada: 13,
    time1: "Corinthians",
    time2: "RB Bragantino",
    data: "2025-07-11",
    hora: "23:00",
    canal: "GLOBO/ PREMIERE",
    estadio: "Neo Química Arena",
    campionato: "Brasileirão"
  },
  {
    rodada: 13,
    time1: "Cruzeiro",
    time2: "Grêmio",
    data: "2025-07-11",
    hora: "23:00",
    canal: "PREMIERE",
    estadio: "Mineirão",
    campionato: "Brasileirão"
  },
  {
    rodada: 13,
    time1: "Flamengo",
    time2: "São Paulo",
    data: "2025-07-11",
    hora: "23:00",
    canal: "GLOBO/ PREMIERE",
    estadio: "Maracanã",
    campionato: "Brasileirão"
  },
  {
    rodada: 13,
    time1: "Fortaleza",
    time2: "Ceará",
    data: "2025-07-11",
    hora: "23:00",
    canal: "RECORD TV/ CAZÉ TV",
    estadio: "Arena Castelão",
    campionato: "Brasileirão"
  },
  {
    rodada: 13,
    time1: "Internacional",
    time2: "Vitória",
    data: "2025-07-11",
    hora: "23:00",
    canal: "PREMIERE",
    estadio: "Beira-Rio",
    campionato: "Brasileirão"
  },
  {
    rodada: 13,
    time1: "Juventude",
    time2: "Sport Recife",
    data: "2025-07-11",
    hora: "23:00",
    canal: "AMAZON PRIME",
    estadio: "Estádio Alfredo Jaconi",
    campionato: "Brasileirão"
  },
  {
    rodada: 13,
    time1: "Mirassol",
    time2: "Fluminense",
    data: "2025-07-11",
    hora: "23:00",
    canal: "PREMIERE",
    estadio: "Estádio Municipal de Mirassol",
    campionato: "Brasileirão"
  },
  {
    rodada: 13,
    time1: "Santos",
    time2: "Palmeiras",
    data: "2025-07-11",
    hora: "23:00",
    canal: "GLOBO/ PREMIERE",
    estadio: "Vila Belmiro",
    campionato: "Brasileirão"
  },
  {
    rodada: 13,
    time1: "Vasco da Gama",
    time2: "Botafogo",
    data: "2025-07-11",
    hora: "23:00",
    canal: "SPORT TV/ PREMIERE",
    estadio: "São Januário",
    campionato: "Brasileirão"
  }
];
 