export default jogos = [
  {
    rodada: 10,
    time1: "São Paulo",
    time2: "Mirassol",
    data: "2025-05-24",
    hora: "18:30",
    canal: "",
    estadio: "Morumbis",
    campionato: "Brasileirão",
  },
  {
    rodada: 10,
    time1: "Fluminense",
    time2: "Vasco da Gama",
    data: "2025-05-24",
    hora: "18:30",
    canal: "",
    estadio: "Maracanã",
    campionato: "Brasileirão",
  },
  {
    rodada: 10,
    time1: "Atlético-MG",
    time2: "Corinthians",
    data: "2025-05-24",
    hora: "21:00",
    canal: "",
    estadio: "Arena MRV",
    campionato: "Brasileirão",
  },
  {
    rodada: 10,
    time1: "Grêmio",
    time2: "Bahia",
    data: "2025-05-25",
    hora: "11:00",
    canal: "",
    estadio: "Arena do Grêmio",
    campionato: "Brasileirão",
  },
  {
    rodada: 10,
    time1: "Palmeiras",
    time2: "Flamengo",
    data: "2025-05-25",
    hora: "16:00",
    canal: "",
    estadio: "Allianz Parque",
    campionato: "Brasileirão",
  },
  {
    rodada: 10,
    time1: "Sport Recife",
    time2: "Internacional",
    data: "2025-05-25",
    hora: "16:00",
    canal: "",
    estadio: "Ilha do Retiro",
    campionato: "Brasileirão",
  },
  {
    rodada: 10,
    time1: "Vitória",
    time2: "Santos",
    data: "2025-05-25",
    hora: "18:30",
    canal: "",
    estadio: "Barradão",
    campionato: "Brasileirão",
  },
  {
    rodada: 10,
    time1: "Fortaleza",
    time2: "Cruzeiro",
    data: "2025-05-25",
    hora: "20:30",
    canal: "",
    estadio: "Castelão",
    campionato: "Brasileirão",
  },
  {
    rodada: 10,
    time1: "RB Bragantino",
    time2: "Juventude",
    data: "2025-05-26",
    hora: "20:00",
    canal: "",
    estadio: "Nabi Abi Chedid",
    campionato: "Brasileirão",
  },
  {
    rodada: 10,
    time1: "Botafogo",
    time2: "Ceará",
    data: "2025-06-04",
    hora: "20:00",
    canal: "",
    estadio: "Nilton Santos",
    campionato: "Brasileirão",
  },



];
 